# Generated by Django 5.0.6 on 2024-06-19 15:22

import django.db.models.deletion
import django.utils.timezone
import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=myapp.models.getFileName)),
                ('additional_image1', models.ImageField(blank=True, null=True, upload_to='additional_cars/')),
                ('additional_image2', models.ImageField(blank=True, null=True, upload_to='additional_cars/')),
                ('additional_image3', models.ImageField(blank=True, null=True, upload_to='additional_cars/')),
                ('price', models.IntegerField(default='')),
                ('kilometer', models.CharField(blank=True, max_length=150, null=True)),
                ('Luggage', models.CharField(max_length=150)),
                ('Seats', models.CharField(max_length=150)),
                ('status', models.BooleanField(default=False, help_text='0-show,1-Hidden')),
            ],
            options={
                'db_table': 'Car',
            },
        ),
        migrations.CreateModel(
            name='LoginData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=50)),
            ],
            options={
                'db_table': 'Loginform',
            },
        ),
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50)),
                ('Email', models.EmailField(default='', max_length=50, validators=[myapp.models.validate_email])),
                ('tellme', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Usermessage',
            },
        ),
        migrations.CreateModel(
            name='MyReserve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Car', models.CharField(max_length=150, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('name', models.CharField(default='', max_length=150)),
                ('age', models.IntegerField(default='', validators=[myapp.models.negative])),
                ('phone_number', models.BigIntegerField(validators=[myapp.models.number])),
                ('email', models.EmailField(default='', max_length=50, validators=[myapp.models.validate_email])),
                ('pickup', models.CharField(default='', max_length=20)),
                ('dropoff', models.CharField(default='', max_length=20)),
                ('pickdate', models.DateField(default=django.utils.timezone.now)),
                ('dropdate', models.DateField()),
                ('picktime', models.TimeField(default='')),
                ('droptime', models.TimeField(default='')),
                ('approved', models.BooleanField(default=False)),
                ('declined', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'MyReserve',
            },
        ),
        migrations.CreateModel(
            name='RegisterData',
            fields=[
                ('username', models.CharField(max_length=50)),
                ('age', models.IntegerField(default='', validators=[myapp.models.negative])),
                ('contact', models.BigIntegerField(primary_key=True, serialize=False, validators=[myapp.models.number])),
                ('email', models.EmailField(default='', max_length=50, validators=[myapp.models.validate_email])),
                ('address', models.CharField(default='', max_length=50)),
                ('password', models.CharField(default='', max_length=20)),
            ],
            options={
                'db_table': 'Registerform',
            },
        ),
        migrations.CreateModel(
            name='MyPassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.registerdata')),
            ],
            options={
                'db_table': 'password_history',
            },
        ),
    ]
