# Generated by Django 5.0.6 on 2024-06-22 15:08

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreserve',
            name='age',
            field=models.IntegerField(default=0, validators=[myapp.models.negative]),
        ),
        migrations.AlterField(
            model_name='myreserve',
            name='droptime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='myreserve',
            name='picktime',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
    ]
