# Generated by Django 5.0.6 on 2024-06-23 15:36

import myapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_myreserve_age_alter_myreserve_droptime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myreserve',
            name='age',
            field=models.IntegerField(default='', validators=[myapp.models.negative]),
        ),
    ]
