# Generated by Django 5.0.6 on 2024-06-23 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_myreserve_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
