# Generated by Django 5.0.6 on 2024-06-24 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdata',
            name='confirm_password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
